name: CI
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'frontend/pnpm-lock.yaml'
      - run: pnpm install --no-frozen-lockfile
        working-directory: frontend
      - run: pnpm lint
        working-directory: frontend
      - run: pnpm build
        working-directory: frontend
      - name: List build output directories
        run: ls -la frontend
      - name: Check if .next directory exists
        run: ls -la frontend/.next || echo ".next directory not found"
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: frontend/.next
          if-no-files-found: warn
